repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports
        exclude: ^grpc_wrapper/
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        exclude: ^grpc_wrapper/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^resources/|^grpc_wrapper/
#  - repo: local
#    hooks:
#      - id: mypy
#        name: Static type checking
#        entry: mypy .
#        language: system
#        pass_filenames: false
#        types: [python]
